version: "2"

services:
  magneticod:
    image: ghcr.io/dir01/magneticod:latest
    volumes:
      - ${MAGNETICOD_DATA}:/root/.local/share/magneticod
      - ${MAGNETICOD_CONFIG}:/root/.config/magneticod
    network_mode: "host"
    command:
      - "--indexer-addr=0.0.0.0:1212"

  magneticow:
    image: ghcr.io/dir01/magneticow:latest
    volumes:
      - ${MAGNETICOD_DATA}:/root/.local/share/magneticod
      - ${MAGNETICOW_CONFIG}:/root/.config/magneticow
    ports:
      - "8080:8080"
