name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: |
        make -j$(nproc) magneticod
        make -j$(nproc) magneticow

    - name: Test
      run: |
        make test

    - name: Lint
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        install-go: false

    - name: Check Formatting
      run: |
        make check-formatting
